version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '[%(asctime)s] %(name)s %(levelname)7s [%(process)5d] | %(message)s'
    datefmt: '%m.%d | %H:%M:%S'
  plain:
    format: '%(name)s - %(message)s'

handlers:
  logfile:
    class: logging.FileHandler
    # provided: ENV (see irt2m/__init__.py)
    filename: "{ENV.DIR.DATA}/irt2m.log"
    formatter: standard
  logfile_libs:
    class: logging.FileHandler
    filename: "{ENV.DIR.DATA}/irt2m.libs.log"
    formatter: standard
  stdout:
    class: logging.StreamHandler
    formatter: plain
    stream: ext://sys.stdout

loggers:
  root:
    level: INFO
    handlers:
      - logfile

  pykeen:
    level: DEBUG
    propagate: true
    handlers:
      - stdout

  wandb:
    level: ERROR
    propagate: false
    handlers:
      - logfile_libs

  pytorch_lightning:
    level: WARNING
    propagate: false
    handlers:
      - logfile_libs
