# given h, r, t \in C:
# torch.real(tensor_product(h, r, torch.conj(t)).sum(dim=-1))

pipeline:
  model: ComplEx
  loss: CrossEntropyLoss

  training_loop: lcwa

  training_kwargs:
    batch_size: 64

