# for available projector models see irt2m.models.PROJECTORS
model: multi context affine projector
model_kwargs:
  pooling: mean

# for available datasets see irt2m.data.PROJECTOR_DATASETS
#   and their respective __init__ methods for *ds_kwargs
#
# contexts_per_sample is the amount of text contexts
# subbatch_size is batch_size if None
module:
  train_ds: vertex ringbuffer
  train_ds_kwargs:
    seed: 5012022
    contexts_per_sample: 10  # per batch
    max_contexts_per_sample: 100
  train_loader_kwargs:
    shuffle: true
    batch_size: 1
    subbatch_size: 10

  valid_ds: mention ringbuffer
  valid_ds_kwargs:
    seed: 5012022
    contexts_per_sample: 10
    max_contexts_per_sample: 100
  valid_loader_kwargs:
    shuffle: false
    batch_size: 1

# for available optimizers see irt2m.models.OPTIMIZERS
optimizer: adam
optimizer_kwargs:
  lr: 1.0e-06
