# for available projector models see irt2m.models.PROJECTORS
model: single context affine projector

# which kgc evaluations to run while training
evaluations:
  - kgc/train         # closed world kgc with original embeddings (run once before training)
  - kgc/transductive  # closed world kgc with projections (irt2.closed_triples)
  - kgc/inductive     # open world kgc with projections (irt2.open_kgc_val*)
  - irt2/inductive    # official irt2 evaluation


# for available datasets see irt2m.data.PROJECTOR_DATASETS
#   and their respective __init__ methods for *ds_kwargs
#
# contexts_per_sample is the amount of text contexts
# subbatch_size is batch_size if None
module:
  train_ds: vertex ringbuffer
  train_ds_kwargs:
    seed: 5012022
    contexts_per_sample: 1  # per batch
    max_contexts_per_sample: 10
    # masking: true
  train_loader_kwargs:
    shuffle: true
    batch_size: 8

  valid_ds: mention flat
  valid_ds_kwargs:
    seed: 5012022
    max_contexts_per_sample: 10
    # masking: true
  valid_loader_kwargs:
    shuffle: false
    batch_size: 60

# for available optimizers see irt2m.models.OPTIMIZERS
optimizer: adam
optimizer_kwargs:
  lr: 5.0e-05

early_stopping: true
early_stopping_kwargs:
  min_delta: 0.001
  patience: 15
  mode: max
  monitor: irt2/inductive/all micro hits@10
